import Config

# 为了便于开发，我们禁用所有缓存，并启用调试和代码重载功能。
#
# 监视器配置可用于运行应用程序的外部监视器。
# 例如，我们可以使用它来打包 .js 和 .css 源文件。
config :equinox, EquinoxWeb.Endpoint,
  # 绑定到环回 IPv4 地址（127.0.0.1）会阻止其他机器访问。
  # 请将其更改为 `ip: {0, 0, 0, 0}` 以允许其他机器访问。
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "l2nIRdT4qYe2oH+eK84r9DunVrxdRHWr6XUgFJe65iw6AV1DzwRL+oTBkWeM/hH3",
  watchers: [
    node: [
      "node_modules/vite/bin/vite.js",
      "build",
      "--watch",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

# ## SSL 支持
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# 当匹配的文件发生更改时，请重新加载浏览器标签页。
config :equinox, EquinoxWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/equinox_web/router\.ex$"E,
      ~r"lib/equinox_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# 启用开发路由（可用于仪表盘）。
config :equinox, dev_routes: true

# 开发日志中不要包含元数据或时间戳。
config :logger, :default_formatter, format: "[$level] $message\n"

# 开发过程中可以设置更高的堆栈跟踪级别。
# 生产环境中应避免进行此类配置，因为构建大型堆栈跟踪可能会消耗大量资源。
config :phoenix, :stacktrace_depth, 20

# 为了加快开发时编译在运行时初始化 plugs
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # 在渲染的标记中包含调试注解和位置信息。
  # 更改此配置需要执行 mix clean 并重新编译。
  debug_heex_annotations: true,
  debug_attributes: true,
  # 启用有用但可能成本高昂的运行时检查
  enable_expensive_runtime_checks: true
