defmodule Equinox.Application do
  @moduledoc false

  use Application

  @impl true
  def start(_type, _args) do
    children = [
      Equinox.Session.Registry,
      {Task.Supervisor, name: Equinox.RenderTaskSupervisor},
      {DynamicSupervisor, name: Equinox.Session.DynamicSupervisor, strategy: :one_for_one},
      Equinox.Kernel.StepRegistry
    ]

    opts = [strategy: :one_for_one, name: Equinox.Supervisor]
    result = Supervisor.start_link(children, opts)

    register_builtin_steps()

    result
  end

  # 这也是个脚手架性质的代码（generated by Gemini）
  # 后面会改成从配置生成
  defp register_builtin_steps do
    alias Equinox.Kernel.StepRegistry

    # Synth nodes
    StepRegistry.register(:phonemizer, %{
      module: Equinox.Steps.Phonemizer,
      inputs: [:notes],
      outputs: [:linguistic],
      options: []
    })

    StepRegistry.register(:acoustic_model, %{
      module: Equinox.Steps.AcousticModel,
      inputs: [:notes, :linguistic],
      outputs: [:mel],
      options: []
    })

    StepRegistry.register(:vocoder, %{
      module: Equinox.Steps.Vocoder,
      inputs: [:mel],
      outputs: [:audio],
      options: []
    })

    # Arranger nodes
    StepRegistry.register(:track_input, %{
      module: Equinox.Steps.TrackInput,
      inputs: [:audio],
      outputs: [:track_out],
      options: [offset_tick: 0, volume: 1.0]
    })

    StepRegistry.register(:mixer, %{
      module: Equinox.Steps.Mixer,
      # 可以接受多个输入，Orchid 支持 List
      inputs: [:tracks],
      outputs: [:mixed],
      options: []
    })

    StepRegistry.register(:master_output, %{
      module: Equinox.Steps.Output,
      inputs: [:mixed],
      outputs: [:master_out],
      options: []
    })
  end

end
