defmodule Equinox.Application do
  @moduledoc false

  use Application

  @impl true
  def start(_type, _args) do
    children = [
      Equinox.Session.Registry,
      Equinox.Kernel.StepRegistry
    ]

    opts = [strategy: :one_for_one, name: Equinox.Supervisor]
    result = Supervisor.start_link(children, opts)

    register_builtin_steps()

    result
  end

  # 这也是个脚手架性质的代码（generated by Gemini）
  # 后面会改成从配置生成
  defp register_builtin_steps do
    alias Equinox.Kernel.StepRegistry

    # Synth nodes
    StepRegistry.register(:phonemizer, Equinox.Steps.Phonemizer)
    StepRegistry.register(:acoustic_model, Equinox.Steps.AcousticModel)
    StepRegistry.register(:vocoder, Equinox.Steps.Vocoder)

    # Arranger nodes
    StepRegistry.register(:track_input, Equinox.Steps.TrackInput)
    StepRegistry.register(:mixer, Equinox.Steps.Mixer)
    StepRegistry.register(:master_output, Equinox.Steps.Output)

    # Oi.Step 的 manifest 不携带默认选项，运行时默认值由 routine 内的
    # Keyword.get 兜底；此处补回注册元数据，保持 palette 契约不变。
    StepRegistry.register_options(:track_input, offset_tick: 0, volume: 1.0)
  end
end
